// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Ciudades
{
    public int IdCiudad { get; set; }

    public string Nombre { get; set; }

    public int? IdLocalidad { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();

    public virtual ICollection<Empleados> Empleados { get; set; } = new List<Empleados>();

    public virtual Localidades IdLocalidadNavigation { get; set; }

    public virtual ICollection<ObrasSociales> ObrasSociales { get; set; } = new List<ObrasSociales>();

    public virtual ICollection<Proveedores> Proveedores { get; set; } = new List<Proveedores>();

    public virtual ICollection<Sucursales> Sucursales { get; set; } = new List<Sucursales>();
}