// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("CIUDADES")]
public partial class Ciudad
{
    [Key]
    [Column("id_ciudad")]
    public int IdCiudad { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [Column("id_localidad")]
    public int? IdLocalidad { get; set; }

    [InverseProperty("IdCiudadNavigation")]
    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    [InverseProperty("IdCiudadNavigation")]
    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    [ForeignKey("IdLocalidad")]
    [InverseProperty("Ciudades")]
    public virtual Localidad? IdLocalidadNavigation { get; set; }

    [InverseProperty("IdCiudadNavigation")]
    public virtual ICollection<ObraSocial> ObrasSociales { get; set; } = new List<ObraSocial>();

    [InverseProperty("IdCiudadNavigation")]
    public virtual ICollection<Proveedor> Proveedores { get; set; } = new List<Proveedor>();

    [InverseProperty("IdCiudadNavigation")]
    public virtual ICollection<Sucursal> Sucursales { get; set; } = new List<Sucursal>();
}