// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Ciudad
{
    public int IdCiudad { get; set; }

    public string Nombre { get; set; }

    public int? IdLocalidad { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    public virtual Localidad IdLocalidadNavigation { get; set; }

    public virtual ICollection<ObrasSocial> ObrasSociales { get; set; } = new List<ObrasSocial>();

    public virtual ICollection<Proveedor> Proveedores { get; set; } = new List<Proveedor>();

    public virtual ICollection<Sucursal> Sucursales { get; set; } = new List<Sucursal>();
}