// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("CLIENTES")]
public partial class Cliente
{
    [Key]
    [Column("id_cliente")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdCliente { get; set; }

    [Column("id_obra_social")]
    public int? IdObraSocial { get; set; }

    [Column("id_ciudad")]
    public int? IdCiudad { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [Column("apellido")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Apellido { get; set; }

    [Column("correo_electronico")]
    [StringLength(80)]
    [Unicode(false)]
    public string? CorreoElectronico { get; set; }

    [Column("calle")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Calle { get; set; }

    [Column("altura")]
    public int? Altura { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    [ForeignKey("IdCiudad")]
    [InverseProperty("Clientes")]
    public virtual Ciudad? IdCiudadNavigation { get; set; }

    [ForeignKey("IdObraSocial")]
    [InverseProperty("Clientes")]
    public virtual ObraSocial? IdObraSocialNavigation { get; set; }
}