// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public int? IdObraSocial { get; set; }

    public int? IdCiudad { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string CorreoElectronico { get; set; }

    public string Calle { get; set; }

    public int? Altura { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Ciudad IdCiudadNavigation { get; set; }

    public virtual ObrasSocial IdObraSocialNavigation { get; set; }
}