// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class DetallesReceta
{
    public int IdDetalleReceta { get; set; }

    public int? IdReceta { get; set; }

    public int? IdSuministro { get; set; }

    public string Descripcion { get; set; }

    public int? Cantidad { get; set; }

    public virtual Recetas IdRecetaNavigation { get; set; }

    public virtual Suministros IdSuministroNavigation { get; set; }
}