// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Empleados
{
    public int LegajoEmpleado { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdCiudad { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Calle { get; set; }

    public int? Altura { get; set; }

    public string CorreoElectronico { get; set; }

    public virtual Ciudades IdCiudadNavigation { get; set; }

    public virtual Sucursales IdSucursalNavigation { get; set; }

    public virtual ICollection<Stocks> Stocks { get; set; } = new List<Stocks>();
}