// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Empleado
{
    public int LegajoEmpleado { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdCiudad { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Calle { get; set; }

    public int? Altura { get; set; }

    public string CorreoElectronico { get; set; }

    public bool? Active { get; set; }

    public string Rol { get; set; }

    public string PasswordEmpleado { get; set; }

    public virtual Ciudad IdCiudadNavigation { get; set; }

    public virtual Sucursal IdSucursalNavigation { get; set; }

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}