// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("FACTURAS")]
public partial class Factura
{
    [Key]
    [Column("nro_factura")]
    public int NroFactura { get; set; }

    [Column("id_cliente")]
    public int? IdCliente { get; set; }

    [Column("id_sucursal")]
    public int? IdSucursal { get; set; }

    [Column("fecha")]
    public DateOnly? Fecha { get; set; }

    [InverseProperty("NroFacturaNavigation")]
    public virtual ICollection<DetalleFactura> DetallesFactura { get; set; } = new List<DetalleFactura>();

    [ForeignKey("IdCliente")]
    [InverseProperty("Facturas")]
    public virtual Cliente? IdClienteNavigation { get; set; }

    [ForeignKey("IdSucursal")]
    [InverseProperty("Facturas")]
    public virtual Sucursal? IdSucursalNavigation { get; set; }
}