// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Facturas
{
    public int NroFactura { get; set; }

    public int? IdCliente { get; set; }

    public int? IdSucursal { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFactura { get; set; } = new List<DetallesFactura>();

    public virtual Clientes IdClienteNavigation { get; set; }

    public virtual Sucursales IdSucursalNavigation { get; set; }
}