// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using JurassicPharm.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace JurassicPharm.Models
{
    public partial interface IJurassicPharmContextProcedures
    {
        Task<int> SP_CONTROLAR_RECETA_PROLONGADAAsync(int? ID_CLIENTE, DateOnly? FECHA_ACTUAL, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_TOP_PROVEEDORES_ENTREGASResult>> SP_TOP_PROVEEDORES_ENTREGASAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
