// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Localidades
{
    public int IdLocalidad { get; set; }

    public string Nombre { get; set; }

    public int? IdProvincia { get; set; }

    public virtual ICollection<Ciudades> Ciudades { get; set; } = new List<Ciudades>();

    public virtual Provincias IdProvinciaNavigation { get; set; }
}