// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("LOCALIDADES")]
public partial class Localidad
{
    [Key]
    [Column("id_localidad")]
    public int IdLocalidad { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [Column("id_provincia")]
    public int? IdProvincia { get; set; }

    [InverseProperty("IdLocalidadNavigation")]
    public virtual ICollection<Ciudad> Ciudades { get; set; } = new List<Ciudad>();

    [ForeignKey("IdProvincia")]
    [InverseProperty("Localidades")]
    public virtual Provincia? IdProvinciaNavigation { get; set; }
}