// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("MEDICOS")]
public partial class Medico
{
    [Key]
    [Column("matricula")]
    public int Matricula { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [Column("apellido")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Apellido { get; set; }

    [Column("correo_electronico")]
    [StringLength(80)]
    [Unicode(false)]
    public string? CorreoElectronico { get; set; }

    [InverseProperty("MatriculaNavigation")]
    public virtual ICollection<Receta> Recetas { get; set; } = new List<Receta>();
}