// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Medico
{
    public int Matricula { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string CorreoElectronico { get; set; }

    public virtual ICollection<Receta> Recetas { get; set; } = new List<Receta>();
}