// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class ObraSocial
{
    public int IdObraSocial { get; set; }

    public string Nombre { get; set; }

    public int? IdCiudad { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual Ciudad IdCiudadNavigation { get; set; }

    public virtual ICollection<Receta> Recetas { get; set; } = new List<Receta>();
}