// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class ObrasSociales
{
    public int IdObraSocial { get; set; }

    public string Nombre { get; set; }

    public int? IdCiudad { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();

    public virtual Ciudades IdCiudadNavigation { get; set; }

    public virtual ICollection<Recetas> Recetas { get; set; } = new List<Recetas>();
}