// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("OBRAS_SOCIALES")]
public partial class ObraSocial
{
    [Key]
    [Column("id_obra_social")]
    public int IdObraSocial { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [Column("id_ciudad")]
    public int? IdCiudad { get; set; }

    [InverseProperty("IdObraSocialNavigation")]
    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    [ForeignKey("IdCiudad")]
    [InverseProperty("ObrasSociales")]
    public virtual Ciudad? IdCiudadNavigation { get; set; }

    [InverseProperty("IdObraSocialNavigation")]
    public virtual ICollection<Receta> Recetas { get; set; } = new List<Receta>();
}