// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("PROVEEDORES")]
public partial class Proveedor
{
    [Key]
    [Column("id_proveedor")]
    public int IdProveedor { get; set; }

    [Column("id_ciudad")]
    public int? IdCiudad { get; set; }

    [Column("razon_social")]
    [StringLength(50)]
    [Unicode(false)]
    public string? RazonSocial { get; set; }

    [ForeignKey("IdCiudad")]
    [InverseProperty("Proveedores")]
    public virtual Ciudad? IdCiudadNavigation { get; set; }

    [InverseProperty("IdProveedorNavigation")]
    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}