// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Provincia
{
    public int IdProvincia { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Localidad> Localidades { get; set; } = new List<Localidad>();
}