// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("PROVINCIAS")]
public partial class Provincia
{
    [Key]
    [Column("id_provincia")]
    public int IdProvincia { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [InverseProperty("IdProvinciaNavigation")]
    public virtual ICollection<Localidad> Localidades { get; set; } = new List<Localidad>();
}