// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Proveedor
{
    public int IdProveedor { get; set; }

    public int? IdCiudad { get; set; }

    public string RazonSocial { get; set; }

    public virtual Ciudad IdCiudadNavigation { get; set; }

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}