// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Proveedores
{
    public int IdProveedor { get; set; }

    public int? IdCiudad { get; set; }

    public string RazonSocial { get; set; }

    public virtual Ciudades IdCiudadNavigation { get; set; }

    public virtual ICollection<Stocks> Stocks { get; set; } = new List<Stocks>();
}