// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Recetas
{
    public int IdReceta { get; set; }

    public int? IdObraSocial { get; set; }

    public int? Matricula { get; set; }

    public virtual ICollection<DetallesReceta> DetallesReceta { get; set; } = new List<DetallesReceta>();

    public virtual ObrasSociales IdObraSocialNavigation { get; set; }

    public virtual Medicos MatriculaNavigation { get; set; }
}