// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("RECETAS")]
public partial class Receta
{
    [Key]
    [Column("id_receta")]
    public int IdReceta { get; set; }

    [Column("id_obra_social")]
    public int? IdObraSocial { get; set; }

    [Column("matricula")]
    public int? Matricula { get; set; }

    [Column("fecha_vencimiento")]
    public DateOnly? FechaVencimiento { get; set; }

    [Column("tipo_receta")]
    [StringLength(50)]
    [Unicode(false)]
    public string? TipoReceta { get; set; }

    [InverseProperty("IdRecetaNavigation")]
    public virtual ICollection<DetalleReceta> DetallesReceta { get; set; } = new List<DetalleReceta>();

    [ForeignKey("IdObraSocial")]
    [InverseProperty("Recetas")]
    public virtual ObraSocial? IdObraSocialNavigation { get; set; }

    [ForeignKey("Matricula")]
    [InverseProperty("Recetas")]
    public virtual Medico? MatriculaNavigation { get; set; }
}