// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Receta
{
    public int IdReceta { get; set; }

    public int? IdObraSocial { get; set; }

    public int? Matricula { get; set; }

    public virtual ICollection<DetalleReceta> DetallesReceta { get; set; } = new List<DetalleReceta>();

    public virtual ObraSocial IdObraSocialNavigation { get; set; }

    public virtual Medico MatriculaNavigation { get; set; }
}