// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace JurassicPharm.Models
{
    public partial class SP_TOP_PROVEEDORES_ENTREGASResult
    {
        public string? razon_social { get; set; }
        [Column("Total Entregado")]
        public int? TotalEntregado { get; set; }
    }
}
