// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("STOCKS")]
public partial class Stock
{
    [Key]
    [Column("id_stock")]
    public int IdStock { get; set; }

    [Column("id_sucursal")]
    public int? IdSucursal { get; set; }

    [Column("id_proveedor")]
    public int? IdProveedor { get; set; }

    [Column("legajo_empleado")]
    public int? LegajoEmpleado { get; set; }

    [Column("cantidad")]
    public int? Cantidad { get; set; }

    [Column("fecha")]
    public DateOnly? Fecha { get; set; }

    [ForeignKey("IdProveedor")]
    [InverseProperty("Stocks")]
    public virtual Proveedor? IdProveedorNavigation { get; set; }

    [ForeignKey("IdSucursal")]
    [InverseProperty("Stocks")]
    public virtual Sucursal? IdSucursalNavigation { get; set; }

    [ForeignKey("LegajoEmpleado")]
    [InverseProperty("Stocks")]
    public virtual Empleado? LegajoEmpleadoNavigation { get; set; }
}