// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Stocks
{
    public int IdStock { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdProveedor { get; set; }

    public int? LegajoEmpleado { get; set; }

    public int? Cantidad { get; set; }

    public DateOnly? Fecha { get; set; }

    public virtual Proveedores IdProveedorNavigation { get; set; }

    public virtual Sucursales IdSucursalNavigation { get; set; }

    public virtual Empleados LegajoEmpleadoNavigation { get; set; }
}