// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("SUCURSALES")]
public partial class Sucursal
{
    [Key]
    [Column("id_sucursal")]
    public int IdSucursal { get; set; }

    [Column("id_ciudad")]
    public int? IdCiudad { get; set; }

    [Column("calle")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Calle { get; set; }

    [Column("altura")]
    public int? Altura { get; set; }

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    [ForeignKey("IdCiudad")]
    [InverseProperty("Sucursales")]
    public virtual Ciudad? IdCiudadNavigation { get; set; }

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}