// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Sucursales
{
    public int IdSucursal { get; set; }

    public int? IdCiudad { get; set; }

    public string Calle { get; set; }

    public int? Altura { get; set; }

    public virtual ICollection<Empleados> Empleados { get; set; } = new List<Empleados>();

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual Ciudades IdCiudadNavigation { get; set; }

    public virtual ICollection<Stocks> Stocks { get; set; } = new List<Stocks>();
}