// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Suministro
{
    public int IdSuministro { get; set; }

    public string Nombre { get; set; }

    public int? PreUnitario { get; set; }

    public int? IdTipoSuministro { get; set; }

    public int? IdTipoDistribucion { get; set; }

    public int? IdMarca { get; set; }

    public virtual ICollection<DetalleFactura> DetallesFactura { get; set; } = new List<DetalleFactura>();

    public virtual ICollection<DetalleReceta> DetallesReceta { get; set; } = new List<DetalleReceta>();

    public virtual Marca IdMarcaNavigation { get; set; }

    public virtual TipoDistribucion IdTipoDistribucionNavigation { get; set; }

    public virtual TipoSuministro IdTipoSuministroNavigation { get; set; }
}