// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("SUMINISTROS")]
public partial class Suministro
{
    [Key]
    [Column("id_suministro")]
    public int IdSuministro { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [Column("pre_unitario")]
    public int? PreUnitario { get; set; }

    [Column("id_tipo_suministro")]
    public int? IdTipoSuministro { get; set; }

    [Column("id_tipo_distribucion")]
    public int? IdTipoDistribucion { get; set; }

    [Column("id_marca")]
    public int? IdMarca { get; set; }

    [Column("stock")]
    public int? Stock { get; set; }

    [Column("stock_minimo")]
    public int? StockMinimo { get; set; }

    [InverseProperty("IdSuministroNavigation")]
    public virtual ICollection<DetalleFactura> DetallesFactura { get; set; } = new List<DetalleFactura>();

    [InverseProperty("IdSuministroNavigation")]
    public virtual ICollection<DetalleReceta> DetallesReceta { get; set; } = new List<DetalleReceta>();

    [ForeignKey("IdMarca")]
    [InverseProperty("Suministros")]
    public virtual Marca? IdMarcaNavigation { get; set; }

    [ForeignKey("IdTipoDistribucion")]
    [InverseProperty("Suministros")]
    public virtual TipoDistribucion? IdTipoDistribucionNavigation { get; set; }

    [ForeignKey("IdTipoSuministro")]
    [InverseProperty("Suministros")]
    public virtual TipoSuministro? IdTipoSuministroNavigation { get; set; }
}