// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class Suministros
{
    public int IdSuministro { get; set; }

    public string Nombre { get; set; }

    public int? PreUnitario { get; set; }

    public int? IdTipoSuministro { get; set; }

    public int? IdTipoDistribucion { get; set; }

    public int? IdMarca { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFactura { get; set; } = new List<DetallesFactura>();

    public virtual ICollection<DetallesReceta> DetallesReceta { get; set; } = new List<DetallesReceta>();

    public virtual Marcas IdMarcaNavigation { get; set; }

    public virtual TiposDistribucion IdTipoDistribucionNavigation { get; set; }

    public virtual TiposSuministro IdTipoSuministroNavigation { get; set; }
}