// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("TIPOS_SUMINISTRO")]
public partial class TipoSuministro
{
    [Key]
    [Column("id_tipo_suministro")]
    public int IdTipoSuministro { get; set; }

    [Column("nombre")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [InverseProperty("IdTipoSuministroNavigation")]
    public virtual ICollection<Suministro> Suministros { get; set; } = new List<Suministro>();
}