// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class TiposDistribucion
{
    public int IdTipoDistribucion { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Suministros> Suministros { get; set; } = new List<Suministros>();
}