// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JurassicPharm.Models;

public partial class TipoSuministro
{
    public int IdTipoSuministro { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Suministro> Suministros { get; set; } = new List<Suministro>();
}