// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Table("TIPOS_DISTRIBUCION")]
public partial class TipoDistribucion
{
    [Key]
    [Column("id_tipo_distribucion")]
    public int IdTipoDistribucion { get; set; }

    [Column("descripcion")]
    [StringLength(50)]
    [Unicode(false)]
    public string? Descripcion { get; set; }

    [InverseProperty("IdTipoDistribucionNavigation")]
    public virtual ICollection<Suministro> Suministros { get; set; } = new List<Suministro>();
}