// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JurassicPharm.Models;

[Keyless]
public partial class ViewFacturacionPorTipo
{
    [Column("Tipo de Suministro")]
    [StringLength(50)]
    [Unicode(false)]
    public string? TipoDeSuministro { get; set; }

    [Column("Total Facturado")]
    public int? TotalFacturado { get; set; }

    [Column("Estado Autorización")]
    [StringLength(16)]
    [Unicode(false)]
    public string EstadoAutorización { get; set; } = null!;
}